# -----------------------------------------------------------------------------
# Kanagawa Paper Canvas
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-canvas.toml
# URL: https://wezterm.org/config/appearance.html
# -----------------------------------------------------------------------------

[colors]
foreground = "#84908e"
background = "#e1e1de"
cursor_bg = "#929fb9"
cursor_border = "#929fb9"
cursor_fg = "#e1e1de"
selection_bg = "#d4cdd4"
selection_fg = "#84908e"
split = "#b0b4c9"
compose_cursor = "#929fb9"
scrollbar_thumb = "#b7b7a9"

ansi = [
  "#b7b7a9",
  "#c58c89",
  "#8ba59e",
  "#b9a679",
  "#91acb8",
  "#a690a8",
  "#929fb9",
  "#b7b7a9",
]
brights = [
  "#bebeb0",
  "#c99895",
  "#93aea7",
  "#c2ae7f",
  "#a0bdca",
  "#af9bb0",
  "#9da8c0",
  "#bebeb0",
]

[colors.indexed]
16 = "#c39e87"
17 = "#c58c89"

[colors.tab_bar]
background = "#d1cfc5"
inactive_tab_edge = "#929fb9"

[colors.tab_bar.active_tab]
fg_color = "#929fb9"
bg_color = "#e1e1de"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#9d9992"
bg_color = "#d1cfc5"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a690a8"
bg_color = "#e1e1de"

[colors.tab_bar.new_tab]
fg_color = "#9d9992"
bg_color = "#d1cfc5"

[colors.tab_bar.new_tab_hover]
fg_color = "#a690a8"
bg_color = "#e1e1de"
intensity = "Bold"

[metadata]
name = "kanagawa-paper-canvas"
author = "Simon Ho"
origin_url = "https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-canvas.toml"
