# -----------------------------------------------------------------------------
# Kanagawa Paper Canvas
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/alacritty/kanagawa-paper-canvas.toml
# URL: https://github.com/alacritty/alacritty
# -----------------------------------------------------------------------------

[colors.primary]
background = '#e1e1de'
foreground = '#73787d'

[colors.cursor]
cursor = '#7e8faf'
text = '#e1e1de'

[colors.selection]
background = '#d4cdd4'
foreground = '#8e8a80'

[colors.normal]
black = '#8e8a80'
red = '#c27672'
green = '#7b958e'
yellow = '#a7956a'
blue = '#809ba7'
magenta = '#9e7e98'
cyan = '#7e8faf'
white = '#b4b4ac'

[colors.bright]
black = '#99958a'
red = '#c68582'
green = '#84a098'
yellow = '#b29f71'
blue = '#91b0bd'
magenta = '#a989a3'
cyan = '#8a9ab8'
white = '#bbbbb3'

[[colors.indexed_colors]]
index = 16
color = '#b28d77'

[[colors.indexed_colors]]
index = 17
color = '#c27672'
